### PR TITLE
Setting up circle ci with config.yml

### PR DESCRIPTION
**Pull request by syed-imam**

### CODE REVIEW

**Comment by paulijones** [comment]
the circleci stuff looks good, I think you just need to stub out the external calls in tests?

**Comment by paulijones** [comment]
just wanted to bump this and see where its at?

**Comment by syed-imam** [comment]
> just wanted to bump this and see where its at?

I have to carve out sometime for this later this week.

**Comment by paulijones** [comment]
@syed-imam we should probably just close this. We've moved to writing all new ci pipelines in github actions instead.

**Pull request closed without merging**
